# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manual_app', '0002_additionaltools_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='next_n',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='manual_app.Nodes'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='prev_n',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='manual_app.Nodes'),
        ),
    ]
