# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_app', '0003_auto_20160929_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='next_n',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='prev_n',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='title',
        ),
        migrations.AddField(
            model_name='nodes',
            name='step_number',
            field=models.IntegerField(default=0),
        ),
    ]
