FROM python:2.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
RUN apt-get update && apt-get install dos2unix
COPY . /app/
RUN pip install --no-deps -r requirements/production.txt
COPY start.sh /start.sh
EXPOSE 8080
RUN python manage.py makemigrations
RUN python manage.py migrate
RUN dos2unix start.sh
CMD /bin/bash ./start.sh