FROM python:2.7
ENV PYTHONUNBUFFERED 1

#Create application directory and setup dependencies
WORKDIR /app
RUN apt-get update && apt-get install -y dos2unix 

#Copy pip dependencies and build
RUN pip install Django==1.10.2 \
djangorestframework==3.4.7 \
mysql-python==1.2.5 \
gunicorn==19.6.0 \
requests

#Copy rest of app and build
WORKDIR /app/
RUN pip install -U nltk
RUN pip install -U numpy
#RUN python -c "import nltk; nltk.download('all', halt_on_error=False)"
ADD . /app/
ADD start.sh /start.sh
RUN pip install bs4==0.0.1

#Expose port, migrate, and run WSGI server
EXPOSE 8080
RUN dos2unix start.sh
CMD /bin/bash ./start.sh